### ISSUE TITLE
keys that contain the dot character are always quoted

### ISSUE THREAD

**Issue by steveeJ** [ordian/toml_edit#232]
hey :wave: 

i'm trying to create a toml that has key names with dot in them as in the following example:

```toml
# nvfetcher.toml
[feeluown-core]
src.pypi = "feeluown"


(...)
```

FYI, this example is taken from the [nvfetcher readme](https://github.com/berberman/nvfetcher#overview).

according to the [toml spec#keys](https://github.com/toml-lang/toml/blob/master/toml.md#keys) these _dotted keys_ are valid and not necessarily quoted. it would be great to have a way to generate toml in this manner with this library.
