### ISSUE TITLE
How to add a table with un-quoted name?

### ISSUE THREAD

**Issue by TimJentzsch** [ordian/toml_edit#330]
I'm trying to add the following to a `Cargo.toml` file:

```toml
[profile.dev]
opt-level = 1
```

I have tried the following:
```rust
let mut dev_profile = Table::new();
dev_profile.insert("opt-level", value(1));

cargo_toml.insert("profile.dev", Item::Table(dev_profile));
```

However, when writing this back to `Cargo.toml` with `cargo_toml.to_string()`, I get the following:
```toml
["profile.dev"]
opt-level = 1
```

Because the `profile.dev` is quoted, Cargo doesn't recognize it as valid key:
```
warning: unused manifest key: profile.dev
```

Is there a way to add it without the quotes?

**Comment by epage** [comment]
> `cargo_toml.insert("profile.dev", Item::Table(dev_profile));`

You are adding a table with the name `profile.dev`.  What you want to do is add the table `profile` and add a table `dev` underneath it.

**Comment by ordian** [comment]
```rust
use toml_edit::*;
 
fn main() {
    let mut doc = Document::new();
    let mut dev_profile = Table::new();
    dev_profile["opt-level"] = value(1);
    let mut profile = Table::new();
    profile.set_implicit(true);
    doc["profile"] = Item::Table(profile);
    doc["profile"]["dev"] = Item::Table(dev_profile);

    println!("{doc}");
}
```
This should work.

**Comment by TimJentzsch** [comment]
Thanks for the quick help, now it works!

While I'm here, is there also a way to add a comment on top of a table?

```toml
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
```
