### ISSUE TITLE
No way to control "decorations" 

### ISSUE THREAD

**Issue by pshirshov** [ordian/toml_edit#93]
I needed to convert a TOML doc like

```toml
[[bins]]
name = 'native-image'

[bins.target]
type = 'Sdk'
name = 'jdk-graal'
```

into equivalent form with inline tables:

```toml
[[bins]]
name = 'native-image'
target ={ type = 'Sdk', name = 'jdk-graal' }

[[bins]]
name = 'gu'
target ={ type = 'Sdk', name = 'jdk-graal' }
```

I managed to do it with `toml_edit`, my solution is insanely dirty, but, thankfully, it works:

```rust
fn make_inline_tbls(paths_arr: &mut ArrayOfTables) {
    for x in (0..paths_arr.len()) {
        let sub = paths_arr.get_mut(x).expect("");
        let tgt_raw = sub.entry("target");

        tgt_raw.as_inline_table_mut().map(|e| e.fmt());
        let tgt_table = tgt_raw.as_table().expect("");
        let mut tgt_inline = InlineTable::default();
        tgt_table.iter().for_each(|i| {
            let key = i.0;
            let value = i.1.as_value().expect("").to_owned();
            tgt_inline.get_or_insert(key, value);
        });
        tgt_inline.fmt();


        let mut tgt_val = Value::InlineTable(tgt_inline);
        let tgt_item = Item::Value(tgt_val);
        *tgt_raw = tgt_item;

    }
}

let mut doc = tout.parse::<Document>().expect("invalid doc");
let bins_arr = doc["bins"].as_array_of_tables_mut().expect("xxx");
make_inline_tbls(bins_arr)
```

But, unfortunately, there is a minor issue with the output doc:

```toml
target ={ type = 'Sdk', name = 'jdk-graal' }
```

There is no space between `=` and `{`. Seems like it's possible to add it using `decor` field but it's private.

Could you please help me?
